version: '3'

services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
    redis:
        image: "redis:alpine"

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.177.57.0/24
